import type {
  Branch,
  BranchActivityLog,
  BranchEmployee,
  BranchInventoryItem,
  BranchTransactionRow,
  BranchUserOption,
} from './types';

const createBranchImage = (label: string, backgroundColor: string) =>
  `data:image/svg+xml;utf8,${encodeURIComponent(
    `<svg xmlns='http://www.w3.org/2000/svg' width='240' height='240'><rect width='100%' height='100%' fill='${backgroundColor}'/><text x='50%' y='54%' text-anchor='middle' dominant-baseline='middle' font-family='Segoe UI, sans-serif' font-size='74' font-weight='700' fill='#FFFFFF'>${label}</text></svg>`
  )}`;

export const BRANCH_OWNER_OPTIONS: BranchUserOption[] = [
  { value: '11', label: 'Patricia Lim' },
  { value: '12', label: 'Marco Reyes' },
  { value: '13', label: 'Lia Tan' },
];

export const BRANCH_MANAGER_OPTIONS: BranchUserOption[] = [
  { value: '1', label: 'Sarah Jenkins' },
  { value: '2', label: 'Miguel Santos' },
  { value: '3', label: 'Anna Cruz' },
  { value: '4', label: 'Kevin Flores' },
];

export const BRANCHES_MOCK: Branch[] = [
  {
    id: 1,
    name: 'Makati HQ',
    address: '120 Ayala Triangle',
    city: 'Makati City',
    contactNumber: '+63 917 801 4101',
    openTime: '07:00',
    closeTime: '22:00',
    ownerUserId: '11',
    owner: 'Patricia Lim',
    managerUserId: '1',
    manager: 'Sarah Jenkins',
    staff: 14,
    status: 'active',
    lowStockItems: 2,
    totalItems: 140,
    notes: 'Flagship store with dual-shift operations.',
    imageUrl: createBranchImage('MH', '#6B4C2A'),
  },
  {
    id: 2,
    name: 'BGC High Street',
    address: '5th Avenue High Street Central',
    city: 'Taguig City',
    contactNumber: '+63 917 612 8842',
    openTime: '08:00',
    closeTime: '23:00',
    ownerUserId: '12',
    owner: 'Marco Reyes',
    managerUserId: '2',
    manager: 'Miguel Santos',
    staff: 8,
    status: 'active',
    lowStockItems: 5,
    totalItems: 110,
    notes: 'Peak demand branch with frequent late-night traffic.',
    imageUrl: createBranchImage('BG', '#546B3F'),
  },
  {
    id: 3,
    name: 'Ortigas Center',
    address: 'Emerald Avenue Corner Garnet Road',
    city: 'Pasig City',
    contactNumber: '+63 917 455 2056',
    openTime: '07:00',
    closeTime: '21:00',
    ownerUserId: '13',
    owner: 'Lia Tan',
    managerUserId: '3',
    manager: 'Anna Cruz',
    staff: 6,
    status: 'active',
    lowStockItems: 0,
    totalItems: 95,
    notes: 'Balanced demand profile, stable inventory turnover.',
  },
  {
    id: 4,
    name: 'Quezon City Circle',
    address: 'Tomas Morato Avenue',
    city: 'Quezon City',
    contactNumber: '+63 917 389 9921',
    openTime: '08:00',
    closeTime: '20:00',
    ownerUserId: '',
    owner: undefined,
    managerUserId: '',
    manager: 'Pending Assignment',
    staff: 0,
    status: 'setup',
    lowStockItems: 0,
    totalItems: 0,
    notes: 'Site setup in progress, user assignments pending.',
  },
];

const BRANCH_EMPLOYEE_ROSTERS: Record<number, BranchEmployee[]> = {
  1: [
    {
      id: 1001,
      branchId: 1,
      firstName: 'Jasper',
      lastName: 'Mendoza',
      position: 'Shift Lead',
      contactNumber: '+63 917 771 2101',
      dateHired: '2025-02-10',
      isActive: true,
    },
    {
      id: 1002,
      branchId: 1,
      firstName: 'Paula',
      lastName: 'Santos',
      position: 'Barista',
      contactNumber: '+63 917 770 1993',
      dateHired: '2025-07-21',
      isActive: true,
    },
    {
      id: 1003,
      branchId: 1,
      firstName: 'Rico',
      lastName: 'Delos Reyes',
      position: 'Cashier',
      contactNumber: '+63 917 553 1329',
      dateHired: '2024-12-04',
      isActive: false,
    },
  ],
  2: [
    {
      id: 2001,
      branchId: 2,
      firstName: 'Ivy',
      lastName: 'Garcia',
      position: 'Shift Lead',
      contactNumber: '+63 917 824 6112',
      dateHired: '2025-03-15',
      isActive: true,
    },
    {
      id: 2002,
      branchId: 2,
      firstName: 'Nikko',
      lastName: 'Panganiban',
      position: 'Barista',
      contactNumber: '+63 917 113 4980',
      dateHired: '2025-08-29',
      isActive: true,
    },
    {
      id: 2003,
      branchId: 2,
      firstName: 'Ella',
      lastName: 'Ramos',
      position: 'Cashier',
      contactNumber: '+63 917 922 7446',
      dateHired: '2025-11-10',
      isActive: true,
    },
  ],
  3: [
    {
      id: 3001,
      branchId: 3,
      firstName: 'Mina',
      lastName: 'Torres',
      position: 'Barista',
      contactNumber: '+63 917 661 0284',
      dateHired: '2024-09-17',
      isActive: true,
    },
    {
      id: 3002,
      branchId: 3,
      firstName: 'Carlo',
      lastName: 'Yu',
      position: 'Shift Lead',
      contactNumber: '+63 917 445 9082',
      dateHired: '2025-01-06',
      isActive: true,
    },
  ],
  4: [],
};

const BRANCH_ACTIVITY_LOGS: Record<number, BranchActivityLog[]> = {
  1: [
    {
      id: 'b1-a1',
      branchId: 1,
      event: 'Completed weekly bean transfer from HQ warehouse',
      actor: 'Sarah Jenkins',
      happenedAt: '2026-04-08T09:42:00Z',
      category: 'inventory',
      outcome: 'successful',
    },
    {
      id: 'b1-a2',
      branchId: 1,
      event: 'Assigned a new shift supervisor to opening shift',
      actor: 'Patricia Lim',
      happenedAt: '2026-04-07T15:10:00Z',
      category: 'staff',
      outcome: 'successful',
    },
    {
      id: 'b1-a3',
      branchId: 1,
      event: 'Daily inventory count flagged syrup variance',
      actor: 'System Monitor',
      happenedAt: '2026-04-07T07:25:00Z',
      category: 'operations',
      outcome: 'flagged',
    },
    {
      id: 'b1-a4',
      branchId: 1,
      event: 'Prepared month-end stock valuation report',
      actor: 'Sarah Jenkins',
      happenedAt: '2026-04-06T17:00:00Z',
      category: 'operations',
      outcome: 'pending',
    },
  ],
  2: [
    {
      id: 'b2-a1',
      branchId: 2,
      event: 'Closed transfer loop for packaging materials',
      actor: 'Miguel Santos',
      happenedAt: '2026-04-08T11:18:00Z',
      category: 'inventory',
      outcome: 'successful',
    },
    {
      id: 'b2-a2',
      branchId: 2,
      event: 'Late-night stock count exceeded variance threshold',
      actor: 'System Monitor',
      happenedAt: '2026-04-07T23:09:00Z',
      category: 'operations',
      outcome: 'flagged',
    },
  ],
  3: [
    {
      id: 'b3-a1',
      branchId: 3,
      event: 'Onboarded one new cashier for weekend shifts',
      actor: 'Anna Cruz',
      happenedAt: '2026-04-07T10:32:00Z',
      category: 'staff',
      outcome: 'successful',
    },
  ],
  4: [],
};

const BRANCH_TRANSACTIONS: Record<number, BranchTransactionRow[]> = {
  1: [
    {
      id: 'b1-t1',
      branchId: 1,
      reference: 'TR-1-0410',
      type: 'Transfer',
      lineItems: 4,
      netChange: 28,
      postedBy: 'Sarah Jenkins',
      timestamp: '2026-04-08T10:10:00Z',
    },
    {
      id: 'b1-t2',
      branchId: 1,
      reference: 'SO-1-0409',
      type: 'Stock-Out',
      lineItems: 6,
      netChange: -19,
      postedBy: 'System Auto',
      timestamp: '2026-04-08T07:35:00Z',
    },
    {
      id: 'b1-t3',
      branchId: 1,
      reference: 'SI-1-0408',
      type: 'Stock-In',
      lineItems: 5,
      netChange: 42,
      postedBy: 'Patricia Lim',
      timestamp: '2026-04-07T13:20:00Z',
    },
    {
      id: 'b1-t4',
      branchId: 1,
      reference: 'ADJ-1-0407',
      type: 'Adjustment',
      lineItems: 2,
      netChange: -3,
      postedBy: 'Sarah Jenkins',
      timestamp: '2026-04-07T11:05:00Z',
    },
  ],
  2: [
    {
      id: 'b2-t1',
      branchId: 2,
      reference: 'SI-2-0408',
      type: 'Stock-In',
      lineItems: 7,
      netChange: 53,
      postedBy: 'Miguel Santos',
      timestamp: '2026-04-08T08:05:00Z',
    },
    {
      id: 'b2-t2',
      branchId: 2,
      reference: 'SO-2-0408',
      type: 'Stock-Out',
      lineItems: 8,
      netChange: -24,
      postedBy: 'System Auto',
      timestamp: '2026-04-08T07:35:00Z',
    },
  ],
  3: [
    {
      id: 'b3-t1',
      branchId: 3,
      reference: 'TR-3-0407',
      type: 'Transfer',
      lineItems: 2,
      netChange: 10,
      postedBy: 'Anna Cruz',
      timestamp: '2026-04-07T12:20:00Z',
    },
  ],
  4: [],
};

const BRANCH_INVENTORY_ITEMS: Record<number, BranchInventoryItem[]> = {
  1: [
    {
      id: 'b1-i1',
      branchId: 1,
      sku: 'BN-ESA-01',
      name: 'Espresso Blend A',
      category: 'Beans',
      supplier: 'Origin Roasters',
      unit: 'kg',
      stockCount: 5,
      reorderPoint: 10,
      status: 'low-stock',
      lastRestocked: '2026-03-29T10:30:00Z',
    },
    {
      id: 'b1-i2',
      branchId: 1,
      sku: 'SY-VAN-02',
      name: 'Vanilla Syrup (1L)',
      category: 'Syrup',
      supplier: 'SweetFlow Trading',
      unit: 'L',
      stockCount: 15,
      reorderPoint: 5,
      status: 'in-stock',
      lastRestocked: '2026-03-20T08:45:00Z',
    },
    {
      id: 'b1-i3',
      branchId: 1,
      sku: 'MK-OAT-01',
      name: 'Oat Milk (1L)',
      category: 'Milk',
      supplier: 'Oatly Pacific',
      unit: 'L',
      stockCount: 8,
      reorderPoint: 15,
      status: 'low-stock',
      lastRestocked: '2026-04-01T11:00:00Z',
    },
    {
      id: 'b1-i4',
      branchId: 1,
      sku: 'PK-CUP-12',
      name: 'Takeaway Cups 12oz',
      category: 'Packaging',
      supplier: 'PackRight PH',
      unit: 'pcs',
      stockCount: 420,
      reorderPoint: 150,
      status: 'in-stock',
      lastRestocked: '2026-04-05T09:10:00Z',
    },
    {
      id: 'b1-i5',
      branchId: 1,
      sku: 'EQ-FLTR-03',
      name: 'Grouphead Filters',
      category: 'Equipment',
      supplier: 'BrewTech Parts',
      unit: 'pcs',
      stockCount: 0,
      reorderPoint: 5,
      status: 'out-of-stock',
      lastRestocked: '2026-03-01T15:20:00Z',
    },
    {
      id: 'b1-i6',
      branchId: 1,
      sku: 'BN-DEC-04',
      name: 'Decaf Beans',
      category: 'Beans',
      supplier: 'Origin Roasters',
      unit: 'kg',
      stockCount: 12,
      reorderPoint: 7,
      status: 'in-stock',
      lastRestocked: '2026-04-06T09:00:00Z',
    },
  ],
  2: [
    {
      id: 'b2-i1',
      branchId: 2,
      sku: 'BN-ESA-01',
      name: 'Espresso Blend A',
      category: 'Beans',
      supplier: 'Origin Roasters',
      unit: 'kg',
      stockCount: 12,
      reorderPoint: 8,
      status: 'in-stock',
      lastRestocked: '2026-03-30T08:00:00Z',
    },
    {
      id: 'b2-i2',
      branchId: 2,
      sku: 'MK-OAT-01',
      name: 'Oat Milk (1L)',
      category: 'Milk',
      supplier: 'Oatly Pacific',
      unit: 'L',
      stockCount: 8,
      reorderPoint: 15,
      status: 'low-stock',
      lastRestocked: '2026-04-01T10:15:00Z',
    },
    {
      id: 'b2-i3',
      branchId: 2,
      sku: 'PK-LID-12',
      name: 'Cup Lids 12oz',
      category: 'Packaging',
      supplier: 'PackRight PH',
      unit: 'pcs',
      stockCount: 610,
      reorderPoint: 220,
      status: 'in-stock',
      lastRestocked: '2026-04-04T12:20:00Z',
    },
  ],
  3: [
    {
      id: 'b3-i1',
      branchId: 3,
      sku: 'BN-ORG-11',
      name: 'Single Origin Beans',
      category: 'Beans',
      supplier: 'Bean Circle Co.',
      unit: 'kg',
      stockCount: 9,
      reorderPoint: 6,
      status: 'in-stock',
      lastRestocked: '2026-04-02T09:25:00Z',
    },
    {
      id: 'b3-i2',
      branchId: 3,
      sku: 'SY-CAR-02',
      name: 'Caramel Syrup (1L)',
      category: 'Syrup',
      supplier: 'SweetFlow Trading',
      unit: 'L',
      stockCount: 2,
      reorderPoint: 5,
      status: 'low-stock',
      lastRestocked: '2026-03-25T11:00:00Z',
    },
  ],
  4: [],
};

export const getBranchById = (branchId: number): Branch | undefined =>
  BRANCHES_MOCK.find((branch) => branch.id === branchId);

export const getBranchEmployeesById = (branchId: number): BranchEmployee[] =>
  BRANCH_EMPLOYEE_ROSTERS[branchId] ?? [];

export const getBranchActivityById = (branchId: number): BranchActivityLog[] =>
  BRANCH_ACTIVITY_LOGS[branchId] ?? [];

export const getBranchTransactionsById = (branchId: number): BranchTransactionRow[] =>
  BRANCH_TRANSACTIONS[branchId] ?? [];

export const getBranchInventoryById = (branchId: number): BranchInventoryItem[] =>
  BRANCH_INVENTORY_ITEMS[branchId] ?? [];
