name: Deploy Kettan OM (Frontend)
on:
  push:
    branches: [ latest ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install & Build
        # This tells GitHub to go INTO the kettan.client folder before running npm
        working-directory: kettan.client
        run: |
          npm install
          npm run build

      - name: Deploy to MonsterASP (FTP)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.OM_FTP_SERVER }}
          username: ${{ secrets.OM_FTP_USERNAME }}
          password: ${{ secrets.OM_FTP_PASSWORD }}
          # The build output will be inside the subfolder's dist directory
          local-dir: ./kettan.client/dist/
          server-dir: /wwwroot/